### ISSUE TITLE
Start the viewController with front cam

### ISSUE THREAD

**Issue by vishalvshekkar** [Awalz/SwiftyCam#10]
Hey,

This is a wonderful library, thank you for this.

I have problem. I want to start my camera view controller with the front camera. If I invoke `switchCamera()` in `viewDidLoad` or `viewWillAppear:animated`, the app crashes with the following message:

[AVCaptureSession stopRunning] stopRunning may not be called between calls to beginConfiguration and commitConfiguration

I assumed that `switchCamera()` stopped the session when it was still being configured.

Then , I tried to set the `currentCamera` property to `.front`, but, that property's setter is private.

Am I missing a way to do this?

**Comment by Awalz** [comment]
Hey vishal,

You will not be able to call `switchCamera()` in `viewDidLoad` or `viewWillAppear:animated`. The AVCaptureSession is configured asynchronously in `viewDidAppear`, so it fail until it has finished configuring.

Currently, there is no way to configure SwiftyCam the way you are asking. I had not considered to add an option for the default. It is something I will add very soon in a future release.

In the meantime, if you need this functionality, you can manually add the source code in the project. on line **143** of SwiftyCamViewController, change the currentCamera to front:
```swift
private(set) public var currentCamera        = CameraSelection.front
```

Should do the trick in the meantime. Ill update this issue once I add the functionality.


Andrew

**Comment by Awalz** [comment]
I have updated the project to support this functionality. You should update your project to version 2.1.0. Then in your `ViewDidLoad`, change the `defaultCamera` property to` .front`: 
 ```swift
override func viewDidLoad() {
    super.viewDidLoad()
    defaultCamera = .front
    ...
}
```
This should do the trick. Let me know if you have any other issues


Andrew

**Comment by vishalvshekkar** [comment]
Hey, thank you for this quick enhancement.

I had done some makeshift changes to make it work with the front cam by default, but, I'm going to pull your changes from v 2.1.0 now.

Have a good one.
