### ISSUE TITLE
bringSubview not work ver. 2.4.x

### ISSUE THREAD

**Issue by masuhara** [Awalz/SwiftyCam#101]
1. UIView(UIButton, UIImageView, etc...) on the Storyboard with IBOutlet.
2. bringSubview_toFront in viewDidLoad func.
3. not showing the view.

**ver.2.2.x works, but 2.4.x does not work.**

```swift
    @IBOutlet weak var takeButton: SwiftyCamButton!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        view.bringSubview(toFront: takeButton)
    }
```

Are there good solutions?

**Comment by Awalz** [comment]
Issue is resolves in 2.6.0. You will no longer need to call bringSubview(toFront:)
