### ISSUE TITLE
Example demo project broken

### ISSUE THREAD

**Issue by Jaspur** [Awalz/SwiftyCam#104]
![schermafdruk 2017-08-24 21 56 22](https://user-images.githubusercontent.com/4254854/29686118-16b96d74-8918-11e7-8d0b-05a74f045e06.png)

**Comment by Awalz** [comment]
Fixed in version 2.6.0

**Comment by Jaspur** [comment]
🎉  thnx

**Comment by renege** [comment]
How to run this example? Because it does not make opening my Simulator. Greetz Rene

**Comment by Awalz** [comment]
You cannot run a camera app in a simulator. You will need a physical device to test the features

**Comment by renege** [comment]
@Awalz nothing is happening when trying to build it to my ipad via xcode
