### ISSUE TITLE
Need progressive duration of video record delegate

### ISSUE THREAD

**Issue by avaan** [Awalz/SwiftyCam#11]
Thanks for your library.
Can you please add a delegate to display or indicate the(progress) duration of the video record in seconds while recording?

**Comment by Awalz** [comment]
Hey there Avaan,

I will look into this as a possible feature for the future.

Currently the delegate has functions:

```swift 
func swiftyCam(_ swiftyCam: SwiftyCamViewController, didBeginRecordingVideo camera: SwiftyCamViewController.CameraSelection)
```

and 

```swift
func swiftyCam(_ swiftyCam: SwiftyCamViewController, didFinishRecordingVideo camera: SwiftyCamViewController.CameraSelection)
```

In your own View Controller subclass, you could create a local timer in `didBeginRecordingVideo` and access the time as this function is called as soon as the video begins recording. That should get you the duration you are looking for.

Let me know if you need a hand


Andrew

**Comment by avaan** [comment]
Thanks Andrew, Currently I implemented the way you suggested.

**Comment by Wndworks** [comment]
@Awalz @avaan Are there any examples of this? 👍
