### ISSUE TITLE
Compiling Errors when trying to use SwiftyCam

### ISSUE THREAD

**Issue by risingsunomi** [Awalz/SwiftyCam#125]
I have used CoCoaPods to install SwiftyCam to a project and I am getting 38 issues seem to be obsoleted issues. All I am doing is importing SwiftyCam to my ViewController.swift (which is giving me a warning that no such module 'SwiftyCam' found) and when building I come up with a lot of issues. Is this project out of date or is this something the xcode 9? Spending hours trying to figure out what the issue is here. Opened it also after pod install with the .xcworkspace file as instructed and still no go. 

<img width="958" alt="screen shot 2017-10-17 at 5 57 02 pm" src="https://user-images.githubusercontent.com/1927935/31697579-ecbff138-b364-11e7-82b7-12ea7ba9ce9c.png">

**Comment by jonandersen** [comment]
Looks like you are using swift 4.  You can use the swift 4 branch
https://github.com/Awalz/SwiftyCam/tree/Swift4

**Comment by risingsunomi** [comment]
Thank you Jon - Also, anyone having further issues and need to use swift4 (using CocoaPods) use this line

<code>
pod 'SwiftyCam', :git => 'https://github.com/Awalz/SwiftyCam.git', :branch => 'Swift4'
</code>

**Comment by sri1sri** [comment]
tanks worked for me and saved my time....
