### ISSUE TITLE
How to install if I am using Swift 4?

### ISSUE THREAD

**Issue by irtefa** [Awalz/SwiftyCam#126]
If I install using cocoapods, I get compiler error e.g. 
`'AVLayerVideoGravityResize' has been renamed to 'AVLayerVideoGravity.resize'`

**Comment by jonandersen** [comment]
Hi @irtefa 

you can use the swift-4 branch to do this:

```
 pod 'SwiftyCam', :git => 'https://github.com/Awalz/SwiftyCam.git', :branch => 'Swift4' 
```

**Comment by papipons** [comment]
Good day! Is the swift-4 branch stable?
