### ISSUE TITLE
Xcode 9 not swift 4.0 compatible?

### ISSUE THREAD

**Issue by RoyalKingMomo** [Awalz/SwiftyCam#128]
Just went ahead and installed via pods and the entire project seemed to have countless compiler errors.

**Comment by brhoomjs** [comment]
**You can change swift version for this pod** 

by going to
 
> Pods -> (left panel) TARGETS -> SwifyCam -> Build Settings -> Swift Language Version 

Make it **3.2**

**Comment by BluePick** [comment]
@brhoomjs Thanks It's working fine...AS OF NOW
