### ISSUE TITLE
Version compatibility

### ISSUE THREAD

**Issue by shemchavez** [Awalz/SwiftyCam#135]
Is SwiftyCam now compatible to Swift 4?

**Comment by risingsunomi** [comment]
Hi,

There is a branch for swift4 on this project that you can choose for cloning/downloading. It will then work with swift4. Let us know any issues you have getting to it. 

![image](https://user-images.githubusercontent.com/1927935/33695996-9c2da444-daac-11e7-8422-86d7a8d793b7.png)

Thanks

**Comment by shemchavez** [comment]
Thanks! 👍

**Comment by jonandersen** [comment]
Cocoapods 3.0.0 is now out with Swift 4.2 support
