### ISSUE TITLE
panGesture is not optional

### ISSUE THREAD

**Issue by thebigkhaled** [Awalz/SwiftyCam#139]
Hello,

PanGesture can interfere with other Scroll recognizer that uses swipe gesture in the same view controller.
It is not possible to remove panGesture (swipe to zoom) from being registered into previewLayer recognizer without altering the source code. This happen due to panGesture is set as private function and no option to remove it from code.

It should allow the following code to run optionally :

```
        if PanGestureEnabled == true {
            panGesture = UIPanGestureRecognizer(target: self, 
                                                        action: #selector(panGesture(pan:)))
            panGesture.delegate = self
            previewLayer.addGestureRecognizer(panGesture)
        }
```

**Comment by Woodyjl** [comment]
Hey,

This was my solution. I used the function below in my view controller to cancel or enable the Swiftycam's pan gesture. Hope this was helpful.

`func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldReceive touch: UITouch) -> Bool {
        print(gestureRecognizer)
        return false
    }`

**Comment by Woodyjl** [comment]
It looks like the panGesture is public now, so you can handle it with delegate functions.

**Comment by yousifa** [comment]
```
swipeToZoom = false
panGesture.isEnabled = false
```

**Comment by thebigkhaled** [comment]
Thanks, I guess that solve it.
