### ISSUE TITLE
iPhone X support

### ISSUE THREAD

**Issue by lynchspin** [Awalz/SwiftyCam#140]
Are there any plans for SwiftyCam to support iPhone X? Specifically configuring the camera to take up the full screen. If this is already supported, please advise me on how to properly configure.

Very much appreciate the help.

**Comment by Woodyjl** [comment]
@lynchspin Just figured out there is already built in iPhone X support just change the videoGravity to .resizeAspectFill before the super.viewDidLoad() or in override the loadView() function in your viewController subclass

**Comment by lynchspin** [comment]
That's awesome. Good stuff @Woodyjl ! Really appreciate it

**Comment by pritesh-uniqual** [comment]
> @lynchspin Just figured out there is already built in iPhone X support just change the videoGravity to .resizeAspectFill before the super.viewDidLoad() or in override the loadView() function in your viewController subclass
> before the super.viewDidLoad()

really very useful, thank you so much
