### ISSUE TITLE
Video compressing

### ISSUE THREAD

**Issue by midgard** [Awalz/SwiftyCam#17]
How do I compress the video output? @Awalz 

Can you add this feature?

**Comment by Awalz** [comment]
This is a feature I would like to add. It will be time consuming as AVAssetReader and AVAssetWriter are not simple API's.

In the short term, I use [SDAVAssetExportSession](https://github.com/rs/SDAVAssetExportSession). Its older and objective-c, but should work fine for compression

**Comment by FaridHaddad** [comment]
Can anyone show me how to use [SDAVAssetExportSession](https://github.com/rs/SDAVAssetExportSession) with SwiftyCam to do a video compression ? I just can't understand how it works.
