### ISSUE TITLE
How can we add stickers on live camera preview with record video?

### ISSUE THREAD

**Issue by kishansuthar** [Awalz/SwiftyCam#180]
hello @Awalz 

After googling more than 5 hours I found your repo to record video . Its really helped me to solve my problems. Now I want to add stickers to live video preview. Can you help me to solve this?

**Comment by jonandersen** [comment]
@kishansuthar  This is currently a little out of the scope for what I would work on adding into this library. However if you are up for the challenge feel free to submit a PR. I think you want to use something like Metal. I found something that had been done before on this: https://github.com/navoshta/MetalRenderCamera

Maybe you can use what's been done there.
