### ISSUE TITLE
Swift 4.2 Support

### ISSUE THREAD

**Issue by Kgroop** [Awalz/SwiftyCam#181]

**Comment by hunterpp** [comment]
@Kgroop I'm feeling a bit of of a lack of support on this project. Can you recommend another more active swift based camera?

**Comment by hunterpp** [comment]
Found one....nm https://github.com/NextLevel/NextLevel

**Comment by jonandersen** [comment]
Check out this branch: https://github.com/Awalz/SwiftyCam/tree/Swift4.2 should have the fixes you need for 4.2.
