### ISSUE TITLE
Cocoapods out of date?

### ISSUE THREAD

**Issue by hunterpp** [Awalz/SwiftyCam#182]
Hi I'm getting a whole bunch of compile errors with cocoapods swiftycam....
<img width="1041" alt="screen shot 2018-09-20 at 8 36 17 pm 1" src="https://user-images.githubusercontent.com/772917/45853764-01629180-bd15-11e8-9517-372fa12a9206.png">

**Comment by jonandersen** [comment]
@hunterpp 3.0.0 was just released and supports swift 4.2
