### ISSUE TITLE
SwiftyCam is compatible with HVec codec ?

### ISSUE THREAD

**Issue by JulienLevallois** [Awalz/SwiftyCam#191]
Hi ! I want to know if we can export videos from SwiftyCam with HVec codec ? not with AVVideoCodecType.h264

Thanks

**Comment by adxworld** [comment]
Theres a big issue for support with this library. Thats the reason I went on and actually deleted it. You rather build the camera fron scratch wont take long. You can download AVCam by apple. It has all the required docs + implementation and also does export HVEC  codecs

**Comment by jonandersen** [comment]
It should be possible to set now: https://github.com/Awalz/SwiftyCam/pull/200
