### ISSUE TITLE
master branch doesn't build

### ISSUE THREAD

**Issue by aried3r** [Awalz/SwiftyCam#198]
https://github.com/Awalz/SwiftyCam/pull/194 introduced Swift 4.2 incompatible changes after the 3.0.0 release.

For example https://github.com/Awalz/SwiftyCam/commit/b0b51e346dbcee34fd06fa379506edc89f0aba57#diff-b8661e0b79eded494b32f6f473e4b648R158 should be `UIControl.State()` and https://github.com/Awalz/SwiftyCam/commit/b0b51e346dbcee34fd06fa379506edc89f0aba57#diff-f569916ddfc3430069279a3f93b0d43cR128 should probably have a default value, maybe `Bool = false {...`.

Maybe to prevent this in the future a Travis build could be added that just tries to compile the library?
https://docs.travis-ci.com/user/languages/objective-c/

**Comment by jonandersen** [comment]
Should have been fixed now, yes adding that would be a good idea. I'll see once I get some more time to improve that!
