### ISSUE TITLE
[SwiftyCam]: Cannot take photo. Capture session is not running

### ISSUE THREAD

**Issue by andrevinic** [Awalz/SwiftyCam#199]
[SWIFT 4.2] I've set all the delegates and methods,

but when I press the button to take photo, it says "[SwiftyCam]: Cannot take photo. Capture session is not running" in the log console.

Does anyone know the solution?

**Comment by miaotaoii** [comment]
same question!!

**Comment by miaotaoii** [comment]
I hava find solution : do not override the  viewWillApperare() method in your view controller

**Comment by andrevinic** [comment]
Awesome, @miaotaoii 

It worked for me also, I had viewWillAppear and I removed it.
Worked.

Maybe we could try to search this bug in the framework and help them fixing it?

**Comment by miaotaoii** [comment]
actually,it's our mistake, we must add  "super.viewWillAppear(animated)"  in our method like this ,

override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
       // your code ...
    },
that because , the code about start session has implemented at parent view controller

**Comment by andrevinic** [comment]
Hum, thats right..
Great one, dude!
    Em quarta-feira, 20 de fevereiro de 2019 22:45:46 BRT, miaotaoii <notifications@github.com> escreveu:  
 
 
actually,it's our mistake, we must add "super.viewWillAppear(animated)" in our method like this ,

override func viewWillAppear(_ animated: Bool) {
super.viewWillAppear(animated)
// your code ...
},
that because , the code about start session has implemented at parent view controller

**Comment by farhanulhaq075** [comment]
> I hava find solution : do not override the viewWillApperare() method in your view controller

Very Helpful Thanks for the Help !

**Comment by weboiOSGaurav** [comment]
> I hava find solution : do not override the viewWillApperare() method in your view controller

Yes, Thanks you so much, it's working fine for me.
