### ISSUE TITLE
Swift 2.3

### ISSUE THREAD

**Issue by ElectrumDevelopment** [Awalz/SwiftyCam#2]
Is there anyway this can be translated to swift 2.3? My whole app is in that version and I'm a bit of a newbie. Thanks!

**Comment by Awalz** [comment]
I will look into this today and see if it is possible

**Comment by Awalz** [comment]
I have looked into it, and I do not believe I can commit to doing this, nor do I think it would be very beneficial for the project going further. If you are unable to update your project (which I think would be the best bet as Swift 3 is awesome) you could look into [manually downgrading the source](http://rebeloper.com/downgrade-swift-3-swift-2-3-xcode-8/). Sorry I couldn't help further

Andrew
