### ISSUE TITLE
Flash not working + Usage needs update?

### ISSUE THREAD

**Issue by smbss** [Awalz/SwiftyCam#20]
I cloned DemoSwiftyCam and tried it on my iPhone 5S but the flash is not working. Is this a framework bug or can you recommend a way to implement it?

Also, comparing the usage instructions on README.md to the DemoSwiftyCam project, I can see that they are not coherent. Do you recommend to continue using the logic on DemoSwiftyCam? 

Thanks in advance!

**Comment by Awalz** [comment]
Hey,

can you point me to where the README differed from the demo, I would love to fix it. I am going to look into the flash issue. Does it not work for all modes (front camera, back camera, photo, video .etc).

Thanks!

**Comment by smbss** [comment]
I'm sorry, it seems that I was misinterpreting the use of SwiftyRecordButton, PhotoViewController and VideoViewController on the DemoSwiftyCam. I thought they were part of the Framework and were not correctly referenced on the usage instructions, but they are just additional classes for further customization.

I was also able to solve the problem with the flash, it seems that there was a conflict with some other Frameworks I was using.

Thank you for your support anyways and keep up the good work!
