### ISSUE TITLE
I have one issue when we are using camera (video call in other any app ex:Skype,Whatssup video call) so and when I want to use the SwiftyCam it should say like Camera is not available or it should not give permission to access camera for SwiftCam how to identify this issue

### ISSUE THREAD

**Issue by ShaikBaji1506** [Awalz/SwiftyCam#211]

**Comment by PingChap** [comment]
find it in ios setting

**Comment by ShaikBaji1506** [comment]
@PingChap  how every time we can't open settings when using SwiftyCam right ? there should be any notification when users camera is being used in other apps or a simple alert would be great

**Comment by dimple039** [comment]
@PingChap did you solve this issue? Can you please guide me on the same?
