### ISSUE TITLE
Long press detection/reponse time?

### ISSUE THREAD

**Issue by midgard** [Awalz/SwiftyCam#22]
@Awalz 

Andrew, i'm pressing to record button. But i guess it is giving late reaction.

I wait for about a second.

Is there a setting for this?

Thank you.

**Comment by midgard** [comment]
I found solution:

    let longGesture = UILongPressGestureRecognizer(target: self, action: #selector(SwiftyCamButton.LongPress))
    longGesture.minimumPressDuration = 0.1;

I've added longGesture.minimumPressDuration parameter to gesture.

I hope this works for anyone.

**Comment by Awalz** [comment]
Thanks for this,

In the future, I would like to make this a configurable variable for SwiftyCamButton. I will add it to the next release. 

Andrew
