### ISSUE TITLE
Background Music Issues

### ISSUE THREAD

**Issue by sulamatraore** [Awalz/SwiftyCam#23]
When I open the camera view controller, the music that is playing immediately stops. When I manage to get music and the camera running, switching the camera from back to front freezes the preview. Is there a reason for this? Thanks in advance!

**Comment by midgard** [comment]
Did you try `allowBackgroundAudio = true` ?

**Comment by Awalz** [comment]
allowBackgroundAudio should be true by default. Are you able to submit your View Controller snippet so I can troubleshoot this further? Thanks

Andrew
