### ISSUE TITLE
Use as photo capture device only

### ISSUE THREAD

**Issue by o15a3d4l11s2** [Awalz/SwiftyCam#24]
Is it possible to use the library only for photo capturing?
At the moment it requests permission to the microphone, but I do not want the users to see such request at all, as I will not record videos. Is this possible with the current implementation?

**Comment by Awalz** [comment]
A photo-only mode has been requested, and will come in Version 3.0 when I have some free time. Currently, there is no way to avoid the permission for microphone. Sorry

Andrew
