### ISSUE TITLE
PreviewLayer view sometimes doesnt Fill Screen

### ISSUE THREAD

**Issue by otymartin** [Awalz/SwiftyCam#25]
@Awalz 
This happens randomly, but when I load the `CameraViewController`, from time to time, the `previewLayer` frame doesnt not extend to the bounds of my screen.

I havent done any modification to the library, simply subclassed `SwiftyCamViewController` with these settings in `viewDidLoad`

Update** I dont know if this could perhaps be the problem `previewLayer = PreviewView(frame: self.view.frame)`. I once read somewhere that you should always use view.bounds not frame but I have yet to test.

```swift
// In viewDidLoad
func cameraSettings() {
        cameraDelegate = self
        defaultCamera = .front
        videoQuality = .medium
        pinchToZoom = false
        flashEnabled = false
        doubleTapCameraSwitch = false
    }
```
![img_4528](https://cloud.githubusercontent.com/assets/2222881/23807426/a210d212-0593-11e7-9444-8153748551bc.PNG)
![img_4527](https://cloud.githubusercontent.com/assets/2222881/23807427/a2114454-0593-11e7-9e2c-e93168a9b479.PNG)

**Comment by Awalz** [comment]
Hey Martin,

Good find! I have not run into this. I have never personally experienced an issue with using the frame, but I could see how it is possible.

Are you presenting the View Controller by itself, or is it embedded in another ViewController?

**Comment by otymartin** [comment]
@Awalz 
Hey I use storyboards and yes I present it by itself.
My `CameraViewController` is in its own storyboard.
```swift
DispatchQueue.main.async {
            self.performSegue(withIdentifier: Segue.camera, sender: self)
        }
```
<img width="258" alt="screen shot 2017-03-10 at 1 33 41 pm" src="https://cloud.githubusercontent.com/assets/2222881/23808073/5178ce88-0596-11e7-84d4-5dbda66031d3.png">

**Comment by Awalz** [comment]
One thing to test would also be if this changes if you explicitly set a resolution, say:

 ``` resolution = .resolution1280x720```

**Comment by otymartin** [comment]
@Awalz 
I did record earlier today and it recorded in 4:3 mode, It played back in 4:3 mode aswell.
I havent done any resolution changes. Theres are the only settings I have which I run at `viewDidLoad`

```swift
func cameraSettings() {
        cameraDelegate = self
        defaultCamera = .front
        videoQuality = .medium
        pinchToZoom = false
        flashEnabled = false
        doubleTapCameraSwitch = false
    }
```

**Comment by Awalz** [comment]
Did you by chance see the resolution the video recorded? 

This is very strange. I do not believe the ```.medium``` setting should include any 4:3
Since the preview and the video recording are the same aspect ratio, I do not believe this issue is the frame. The preview frame does not impact the actual recording. The fact that the recording was 4:3 points to an issue with the AVCapturePreset.

For a temporary fix, I would change your preset  to  ```.resolution1280x720``` (which for most devices is the same as ```.medium```.

Also, what device were you able to reproduce this on?

Thanks 

Andrew

**Comment by otymartin** [comment]
I changed to `.resolution1280x720`
Im using `iPhone 6`
![img_4536](https://cloud.githubusercontent.com/assets/2222881/23808476/04d66052-0598-11e7-8791-aefcbfccaaee.PNG)

**Comment by Awalz** [comment]
Ok. I will try to do some testing with an iPhone 6.

**Comment by otymartin** [comment]
@Awalz Yea i will post as soon as I get results, Its hard to reproduce because it happens randomly
But I will be printing out, `View.frame, view.bounds, previewLayer.frame, previewLayer.bound and video metadata`

**Comment by otymartin** [comment]
@Awalz i've only been able to replicate this while device is disconnected from my macbook. very odd!

**Comment by otymartin** [comment]
@Awalz 
So this issue still happens but for some reason I cant get it to show up when device is connected to macbook. Here are the info on the outputed video which I downloaded to my computer.
`Kind: MPEG-4 movie`
`Dimensions: 360 × 480`
`Codecs: AAC, H.264`
Hope its usefull somehow

**Comment by Awalz** [comment]
Are you converting the video at all?

It should be QuickTime video, not MPEG-4 movie. Very strange

**Comment by otymartin** [comment]
@Awalz 
Yes I convert to `MP4`

**Comment by otymartin** [comment]
@Awalz 
Slight update on this issue.
Theres another issue that sprung up recenly which is in `viewDidLoad` i set my `front` camera as `default`
```swift
func cameraSettings() {
        cameraDelegate = self
        defaultCamera = .front
        videoQuality = .medium
        pinchToZoom = false
        flashEnabled = false
        doubleTapCameraSwitch = false
    }
```

However from time to time, it loads the rear camera instead.
So as a temporary patch job in `viewDidAppear` I do a check then switch camera incase the `rear` cam loads. Bare in mind I want to force the use of front camera without option to use rear.
```swift
if self.currentCamera == .rear {
            self.switchCamera()
        }
```

An interesting thing that happened is when I was loading the app, the original issue appeared which is the `360 x 480` preview layer instead of fullscreen. And the camera was also `rear facing`. Then when the `switchCamera` code ran, it switched to `front-camera` and loaded to the full iPhone 6 screen.

Hope that provides some hints.

**FYI** I commented out this code in `viewDidDisappear` because I want the session to keep running when the `PreviewViewController` loads after `didFinishRecordingVideo` because when user goes back to `CameraViewController`, I dont want there to be lag.
```swift
// If session is running, stop the session
        /*if self.isSessionRunning == true {
            self.session.stopRunning()
            self.isSessionRunning = false
        }*/
```

**Comment by david-koch-pro** [comment]
I have also same experience with this issue. My face camera was not full screen using this camera.

**Comment by Awalz** [comment]
I have been unable to reproduce this issue. I have tested with multiple devices running different software versions.

If someone could provide a sample project or more code snippets, it would help to narrow this down
