### ISSUE TITLE
maximumVideoDuration = 10.0 NOT WORKING !!

### ISSUE THREAD

**Issue by SimoMazil** [Awalz/SwiftyCam#26]
override func viewDidLoad() {
        super.viewDidLoad()
maximumVideoDuration = 120.0 
}

and after 2 minutes the video does not finish recording !

**Comment by Awalz** [comment]
You will need to provide more information than a title. Please update the issue

Andrew

**Comment by SimoMazil** [comment]
done

**Comment by Awalz** [comment]
Please check out the README or look at the demo example. The maximumVideoDuration does not apply to all recorded video, only video recording controlled by an instance of SwiftyCamButton. If you wish to have a maximum duration and not use a SwiftyCamButton, you will need to create your own timer and handle in manually.

Andrew

**Comment by SimoMazil** [comment]
Ok Thanks
