### ISSUE TITLE
SwiftyCamDidTakePhoto returns rotated image

### ISSUE THREAD

**Issue by ryandailey100** [Awalz/SwiftyCam#3]
I noticed a small bug when taking a picture with the front facing camera. The image that gets returned is rotated 180 degrees. This is only the case when taking the picture with the front facing camera, not the rear camera.

**Comment by Awalz** [comment]
Thanks for the heads up. Ill fix this right away!


Andrew

**Comment by Awalz** [comment]
I believe I have resolved this issue. Let me know if you still see it on the new version (1.1.4)


Andrew

**Comment by ryandailey100** [comment]
Works great! Thanks for the fix 👍
