### ISSUE TITLE
Unable to capture media

### ISSUE THREAD

**Issue by david-koch-pro** [Awalz/SwiftyCam#31]
When push camera viewcontroller, I could see the following message.

Domain=AVFoundationErrorDomain Code=-11814 "Cannot Record" UserInfo={NSLocalizedRecoverySuggestion=Try recording again., NSLocalizedDescription=Cannot Record}

What should I fix?

**Comment by Awalz** [comment]
Can you provide the source code or a sample project where this reproducible? I have never encountered this error

**Comment by david-koch-pro** [comment]
I've checked my source again and guessing this part has problem. (I modified if condition because original code is deprecated)

```
fileprivate class func deviceWithMediaType(_ mediaType: String, preferringPosition position: AVCaptureDevicePosition) -> AVCaptureDevice? {
        if let devices = AVCaptureDeviceDiscoverySession(deviceTypes: [], mediaType: mediaType, position: position).devices {
            return devices.filter({ $0.position == position }).first
        }
        return nil
    }
```

**Comment by Awalz** [comment]
AVCaptureDeviceDiscoverySession is only available in iOS 10. The framework supports iOS 8+. Does the issue persist if you ignore the deprecation warnings and run the source code as it?

**Comment by david-koch-pro** [comment]
If I ignore the deprecation warnings, it's running well...

**Comment by david-koch-pro** [comment]
I was wrong. Added deviceTypes and running well.
`let devices = AVCaptureDeviceDiscoverySession(deviceTypes: [AVCaptureDeviceType.builtInWideAngleCamera], mediaType: mediaType, position: position).devices`

**Comment by Awalz** [comment]
Sorry you were wrong about what? That its running well with the original source, or that that was the part of the refactored code that is giving you problems?

**Comment by david-koch-pro** [comment]
Original source is running well and new code fixed for deprecation is also running well.
