### ISSUE TITLE
Zoom by sliding up or down

### ISSUE THREAD

**Issue by JayBone16** [Awalz/SwiftyCam#32]
In future versions could this be integrated.

**Comment by Awalz** [comment]
Yes definitely. I will look into this for the next release

Andrew

**Comment by marcosgriselli** [comment]
Is there any milestone for this and #7? I can help out.

**Comment by Awalz** [comment]
@marcosgriselli zoom by sliding will be implemented on the next release. #7 will be fairly complicated, and I do not believe I will be able to tackle it as I lack the knowledge of AVAssetReader/AVAssetWriter. I would love assistance!

**Comment by Awalz** [comment]
This feature has been added to Version 2.3.0
