### ISSUE TITLE
How to take photos and record video in a different aspect ratio

### ISSUE THREAD

**Issue by JayBone16** [Awalz/SwiftyCam#33]
Hi,
I would like to take photos and record video in a different ratio other then 16:9
I would like it to be something more custom like 3:4.

**Comment by JayBone16** [comment]
It has to be in a high video quality mode

**Comment by Awalz** [comment]
SwiftyCam does not support any aspect ratios other than 16:9. It uses the AVCaptureSessionPresets in AVFounfation
The only supported 4:3 aspect ratios are 640x480 and 320x240, which are low quality and not included in SwiftyCam
