### ISSUE TITLE
Square photo

### ISSUE THREAD

**Issue by kocoai** [Awalz/SwiftyCam#36]
Hi,

It's possible to change the photo capture aspect ratio to 1:1 without cropping the output ?

Thanks

**Comment by Awalz** [comment]
It is not currently possible as SwiftyCam does not do any processing of the video output. You would need to handle that with `AVAssetReader` and `AVAssetWriter`

**Comment by kocoai** [comment]
I understand that :), my question is about the possibility to modify the aspect ratio of the input (without processing the output)... but it seem there is no possibility

**Comment by Awalz** [comment]
It would required Apple to have an AVCaptureSessionPreset that is square. I would love to be able to support it.

Your best bet is to add a mask over the preview layer to simulate a square view finder, then use a library like [SDAVAssetExportSession](https://github.com/rs/SDAVAssetExportSession) to export the captured video to square. I have had some success with this method

Hope you find your solution

Andrew

**Comment by kocoai** [comment]
Yes thank you for your advice
