### ISSUE TITLE
Consecutive Taps Crash

### ISSUE THREAD

**Issue by Qianen1111** [Awalz/SwiftyCam#37]
Hey there,

When doubleTapCameraSwitch is enabled, tapping a few extra times consecutively causes an error:
*** Terminating app due to uncaught exception 'NSGenericException', reason: '*** -[AVCaptureSession stopRunning] stopRunning may not be called between calls to beginConfiguration and commitConfiguration'

Thanks,
Qianen

**Comment by Awalz** [comment]
Thanks for the heads up. This will be fixed on the next release

**Comment by Awalz** [comment]
Issue should be resolved in version 2.2.2
