### ISSUE TITLE
Is there any way to completely remove whatever makes it ask for microphone permission?

### ISSUE THREAD

**Issue by hollowaytyl** [Awalz/SwiftyCam#40]
Hello,

I'm building a database with SwiftyCam and I've been having some problems uploading the videos to my server but the pictures work fine. So right now I want to just go with photo upload as I have removed the ability for users to create videos (I'd really love adding this back one day). Everything is fine but it's kind of creepy that my app asks for microphone permission but doesn't utilize it. 

I've removed some of the privacy settings in the info.plist related to this, however as you may already know, it just removed the details/reason for asking for permission but the notification still persists. Are you able to tell me what triggers SwiftyCam to ask for this permission and how I can remove it for now?

I've tried removing some AVCaptureSession() stuff but it pretty much breaks everything - I'm hoping the solution is a one-liner.

Thanks for any help, I absolutely love all the hard work you put into this.

**Comment by Awalz** [comment]
This is possible by not adding the Audio Input when the session is configured our monitored. This will (should) still allow video capture without audio. Here's the code example if you want to fork and try it yourself (the add audio input is commented):

	/// Configure session, add inputs and outputs

	fileprivate func configureSession() {
		guard setupResult == .success else {
			return
		}

		// Set default camera

		currentCamera = defaultCamera

		// begin configuring session

		session.beginConfiguration()
		configureVideoPreset()
		addVideoInput()
		//addAudioInput()
		configureVideoOutput()
		configurePhotoOutput()

		session.commitConfiguration()
	}

	/// Add inputs after changing camera()

	fileprivate func addInputs() {
		session.beginConfiguration()
		configureVideoPreset()
		addVideoInput()
		//addAudioInput()
		session.commitConfiguration()
	}

I hope to add this as a feature in the future, but will require some testing

**Comment by hollowaytyl** [comment]
Perfect! Everything is working nicely. Will stay posted for any further updates. Thanks for your timely response as always.

**Comment by rivera-ernesto** [comment]
Seems to be implemented natively here https://github.com/Awalz/SwiftyCam/commit/5fcc21edf9b313480e118586631b71b380b3a6e5. Just CocoaPods' 2.4.0 pending?

**Comment by Awalz** [comment]
Yes sorry. The pod has just been updated
