### ISSUE TITLE
Camera not coming in Full screen in iPad.

### ISSUE THREAD

**Issue by goyalhonney** [Awalz/SwiftyCam#41]

**Comment by Awalz** [comment]
This issue will need additional information. Please update with a description, device, SwiftyCam version and iOS version

**Comment by goyalhonney** [comment]
I am using Ipad Air 2 with ios 10.3.1 with latest Swiftycam version.
Problem is that Camera is not occupying the entire screen when I run this on my Iphone 6s with ios 10.3.1 it works fine.

**Comment by Awalz** [comment]
Can you try it with the latest release (2.2.2). Screenshots would be helpful with any orientation info

**Comment by Awalz** [comment]
This should be resolved with the changes in 2.3.0. If it is not, please open a new issue with detailed information, including screenshots.

Thanks

Andrew
