### ISSUE TITLE
Single Tap problem

### ISSUE THREAD

**Issue by midgard** [Awalz/SwiftyCam#42]
Hi @Awalz,

I commented some lines on SwiftyCamButton.swift file.

Like; let tapGesture and self.addGestureRecognizer(tapGesture) but single tap still working. This triggers longGesture.

Why? I Updated pod and i have this problem.

Thanks

**Comment by Awalz** [comment]
What is it you are trying the achieve?

**Comment by Awalz** [comment]
I am closing this issue. If you are having further problems, please open a new issue with detailed issues of what you are trying to achieve, and the current issue you are facing.
