### ISSUE TITLE
Swipe up for camera roll/button to access camera roll

### ISSUE THREAD

**Issue by jjjeeerrr111** [Awalz/SwiftyCam#46]
Would be nice to have the option to pick an image/video from the camera roll without having to exit the swifty cam controller. The functionality could be a camera roll icon and a swipe up to drag the camera roll up

**Comment by Awalz** [comment]
I will look into this for possible future enhancements

**Comment by jonchui** [comment]
so @Awalz did you decide not to do this?

**Comment by dfmarulanda** [comment]
There is any update on this?
