### ISSUE TITLE
Some Suggestion...

### ISSUE THREAD

**Issue by unittesting0** [Awalz/SwiftyCam#5]
Some feedback for the SwiftyCam:

1. Disable Zoom when switching to front Camera (It doesn't zoom but the values change in the console, and when I switch to back camera and when I start to zoom it goes immediately at the highest value where I left from front camera.

2. Changing Icon when the light is on and off.

3. Disabling flash icon on front camera or taking a flash (like the iPhone camera or like snap)

4. When recording making an animation like Snapchat that you are recording (the red circle animated).

5. What do you think making a double tap to change the camera from back to front and vice versa.

Thanks

**Comment by Awalz** [comment]
Thanks for the heads up about the zoom issue. Was an oversight on my part and has been resolved.

I like your idea for a better demo. I  definitely would like to put together something a little better. Double tapping to switch camera could be neat, ill look into it!

Andrew
