### ISSUE TITLE
Video Recording Long Press Gesture Problem

### ISSUE THREAD

**Issue by umutdonmez8** [Awalz/SwiftyCam#55]
Hi Andrew,

I have a problem while video recording. As follows:
Very short Long press duration  on SwiftyCamButton causes endless video recording. 
In my debug session, I saw all UIGestureRecognizerState.began and UIGestureRecognizerState.ended state code blocks called. But recording never stopped

Thanks for help

**Comment by Awalz** [comment]
This issue should be fixed on the newest version.

Let me know if issue still persists

**Comment by Jitenderios** [comment]
hi @Awalz,

This issue is still there.
https://github.com/Awalz/SwiftyCam/issues/146
