### ISSUE TITLE
Working with Navigation Controller

### ISSUE THREAD

**Issue by caesss** [Awalz/SwiftyCam#56]
First of Thanks for the great work. It appears that setting this controller as part of NavigationController causes the previewLayer to not size properly on deviceRotation. Maybe I'm missing something but if not please consider this case. For now, I'm using it as a standalone ViewController and it all works very well. 

Thank you again!

**Comment by Awalz** [comment]
This should be fixed on the newest version. If is it not, please submit a new issue. A screenshot would help!

Andrew
