### ISSUE TITLE
PanGesture

### ISSUE THREAD

**Issue by caesss** [Awalz/SwiftyCam#57]
I'm not sure this is an issue but rather a question. I'm trying to use a panGesture in my Controller to handle a transition to dismiss the CameraController. I've set swipeToZoom to false but that just turns off the execution of the code within the selector. I'm trying to remove the pangesture all together. I know I can just comment out 

        //let panGesture = UIPanGestureRecognizer(target: self, action: #selector(panGesture(pan:)))
        //panGesture.delegate = self
        //view.addGestureRecognizer(panGesture)

1. Is it possible to remove the panGesture from within my controller without modifying your code. 
2. Is it possible to leave your panGesture but also make sure the code in my Gesture executes? (mine is a swipe left to right) whereas Zoom in top to bottom.

**Comment by Awalz** [comment]
In the newest version, I have exposed both the `panGesture` and `pinchGesture` used for zoom. You should be able to add an additional action to them, and they will not interfere. No need to add a second panGesture

Let me know if it is still not working

Andrew
