### ISSUE TITLE
Could not create video device input: Error Domain=AVFoundationErrorDomain Code=-11814

### ISSUE THREAD

**Issue by zakdances** [Awalz/SwiftyCam#58]
Using XCode 8.3 with an iOS 10.3 target. I get this error whenever I designate a ViewController as `SwiftyCamViewController` as per the ReadMe instructions.
 
```
[SwiftyCam]: Could not create video device input: Error Domain=AVFoundationErrorDomain Code=-11814 "Cannot Record" UserInfo={NSLocalizedDescription=Cannot Record, NSLocalizedRecoverySuggestion=Try recording again.}
[SwiftyCam]: Could not create audio device input: Error Domain=AVFoundationErrorDomain Code=-11814 "Cannot Record" UserInfo={NSLocalizedDescription=Cannot Record, NSLocalizedRecoverySuggestion=Try recording again.}
```

**Comment by caesss** [comment]
Make sure you are running your code on an actual device and NOT the emulator. Also make sure you've updated the info.plist with this: 
<key>NSCameraUsageDescription</key>
	<string>$(PRODUCT_NAME) Needs to access your camera to take photos and video.</string>

**Comment by zakdances** [comment]
That was my mistake, thanks.
