### ISSUE TITLE
Flash not working

### ISSUE THREAD

**Issue by ryandailey100** [Awalz/SwiftyCam#6]
I am having issues getting the flash to work on the latest build. When I set  flashEnabled = true , it does nothing. Any idea why this doesnt work?

EDIT: This ended up being something on my end. Sorry about that! Flash is working just as expected.

**Comment by Awalz** [comment]
Ok sounds good! The behaviour of the flash has changed with the new update to be more similar to Snapchat. Let me know if you are having more problems 

Andrew
