### ISSUE TITLE
Not fullscreen on iPad

### ISSUE THREAD

**Issue by smidaren** [Awalz/SwiftyCam#60]
The camera is not in fullscreen when running on iPad

**Comment by Awalz** [comment]
This is due to the Aspect Ratio of the capture session being 16:9.

I have added a `videoGravity` property which changes the contentMode of the preview view. You should be able to change this to fill the screen of the iPad

Andrew

**Comment by jonchui** [comment]
FYI, if you model your camera after their example code and subclass `SwiftyCamViewController`, you have to set the videoGravity before you call `super.viewDidLoad` since that is where the videoGravity variable gets passed in.
