### ISSUE TITLE
Square Image/Video capture

### ISSUE THREAD

**Issue by Minebomber** [Awalz/SwiftyCam#64]
Hello, I am using this library, but I need to get a square image. Is there a setting for this? (if there is not,  could it be possible to crop it after its taken?

**Comment by Awalz** [comment]
There is no current setting for this. You would need to crop the image after it is taken.

I recommend adding overlay views overtop the camera to give the appearance of a square view finder, then cropping the centre of the image into a square once it is taken.

Good luck!
