### ISSUE TITLE
Make camera for video use only

### ISSUE THREAD

**Issue by lynchspin** [Awalz/SwiftyCam#67]
Is there any property that I can set on the SwiftyCamButton to explicitly state that I will be using the camera for video only?

**Comment by Awalz** [comment]
Not currently,

I would recommend making your own, custom button that calls `startRecording` and `stopRecording`. That way your app will not take photos

**Comment by lynchspin** [comment]
Ok, gotcha. So I created a button with a long press recognizer and when I call `startRecording`, I get this error: 

"[SwiftyCam]: Movie file finishing error: Optional(Error Domain=AVFoundationErrorDomain Code=-11859 "Movie recording cannot be started" UserInfo={NSUnderlyingError=0x170a543a0 {Error Domain=NSOSStatusErrorDomain Code=-16419 "(null)"}, NSLocalizedFailureReason=A movie recording is already in progress., NSLocalizedRecoverySuggestion=Stop the movie recording in progress and try again."

Would you have any idea what might be triggering this?

**Comment by Awalz** [comment]
Can you send a code snippet of your custom button?

On Sat, Jun 10, 2017 at 2:47 PM Joseph

<
mailto:Joseph <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Ok, gotcha. So I created a button with a long press recognizer and when I call

startRecording

, I get this error:

"[SwiftyCam]: Movie file finishing error: Optional(Error Domain=AVFoundationErrorDomain Code=-11859 "Movie recording cannot be started" UserInfo={NSUnderlyingError=0x170a543a0 {Error Domain=NSOSStatusErrorDomain Code=-16419 "(null)"}, NSLocalizedFailureReason=A movie recording is already in progress., NSLocalizedRecoverySuggestion=Stop the movie recording in progress and try again."

Would you have any idea what might be triggering this?

—

You are receiving this because you modified the open/close state.

Reply to this email directly,
https://github.com/Awalz/SwiftyCam/issues/67#issuecomment-307589323
, or

**Comment by lynchspin** [comment]
//Create Button for recording
`let captureButton = UIButton (frame: CGRect(x: self.view.frame.size.width/2 - 70, y: self.view.frame.size.height - 160, width: 140, height: 140))
        captureButton.setImage(UIImage(named: "CameraButtonWhite"), for: .normal)
        let longPressRecognizer = UILongPressGestureRecognizer(target: self, action: #selector(longPressed(sender:)))
        longPressRecognizer.delegate = self
        self.view.addGestureRecognizer(longPressRecognizer)
        cameraDelegate = self`

//Function called when long press occurs
`func longPressed(sender:UILongPressGestureRecognizer) {
        self.startVideoRecording()
    }`

//Delegate Method called
`   func swiftyCam(_ swiftyCam: SwiftyCamViewController, didBeginRecordingVideo camera: SwiftyCamViewController.CameraSelection) {
        // Called when startVideoRecording() is called
        // Called if a SwiftyCamButton begins a long press gesture
        
        self.addCircleView()
        self.holdLabel.isHidden = true
        self.flashOnOffButton.isHidden = true
        self.cancelButton.isHidden = true
        self.flipCameraButton.isHidden = true
        
    }`

If you need any other snippets, let me know. I think the above is all the pertinent parts. Thanks for the help.

**Comment by lynchspin** [comment]
`override func viewDidLoad() {
        super.viewDidLoad()
        
        //Create Button for recording
        let captureButton = UIButton (frame: CGRect(x: self.view.frame.size.width/2 - 70, y: self.view.frame.size.height - 160, width: 140, height: 140))
        captureButton.setImage(UIImage(named: "CameraButtonWhite"), for: .normal)
        let longPressRecognizer = UILongPressGestureRecognizer(target: self, action: #selector(longPressed(sender:)))
        longPressRecognizer.delegate = self
        self.view.addGestureRecognizer(longPressRecognizer)
        cameraDelegate = self`
`func longPressed(sender:UILongPressGestureRecognizer) {
        self.startVideoRecording()
    }
}`


'func swiftyCam(_ swiftyCam: SwiftyCamViewController, didBeginRecordingVideo camera: SwiftyCamViewController.CameraSelection) {
        self.addCircleView()
        self.holdLabel.isHidden = true
        self.flashOnOffButton.isHidden = true
        self.cancelButton.isHidden = true
        self.flipCameraButton.isHidden = true
        
    }'

Sorry, cleaned up the snippets for you.

And if you need any other snippets, let me know. I think the above is all the pertinent parts. Thanks for the help.

**Comment by lynchspin** [comment]
Figured it out... `longPressed`was getting called multiple times. So I added a simple conditional to check if it was already recording. I appreciate the help
