### ISSUE TITLE
Switch cameras while recording?

### ISSUE THREAD

**Issue by HackShitUp** [Awalz/SwiftyCam#7]
Have you implemented the ability to switch the front facing and back facing cameras while the video is recording?

**Comment by Awalz** [comment]
I have not implemented this feature. It is a feature I would very much like to add. It would require a somewhat extensive rewrite of the `movieFileOutput` and I would have to manually write an AVAssetExporter. I can't promise this feature been added in the near future

Andrew

**Comment by HackShitUp** [comment]
I can try and implement it @Awalz but I have a problem...
I've never contributed to with Github before. Mind if I send you the source file via email?

**Comment by HackShitUp** [comment]
@Awalz when I finish?

**Comment by Awalz** [comment]
You can if you wish.

Submitting a pull request isn't that bad. You call follow [this link](https://help.github.com/articles/creating-a-pull-request/) and see how you do when you have something complete. That way you will get credit as a contributor. Its up to you though.

Let me know if you need a hand.

Andrew
