### ISSUE TITLE
Pod install issue

### ISSUE THREAD

**Issue by Yin327** [Awalz/SwiftyCam#71]
Hello 
I can't install SwiftyCam from podfile

I can see "Unable to find a soecification for 'SwfityCam'"

pod 'SwiftyCam'

Please help me what is problem

Thanks

**Comment by Awalz** [comment]
I just tested and `pod 'SwiftyCam'` in the podfile works without issue.

You will need to provide more information

**Comment by Yin327** [comment]
[Documents.zip](https://github.com/Awalz/SwiftyCam/files/1078402/Documents.zip)

I attach pod install issue screenshot and my pod file

**Comment by Awalz** [comment]
I was just able to install all of your pods using a test project, including SwiftyCam.

I am unsure of your issue. Can you create a test project with Cocoapods , include SwiftyCam, and try to install the pods?

**Comment by Yin327** [comment]
ok, it seems my pod version was old.
I have updated my cocoapods and now it works well
Thanks for your effort.
