### ISSUE TITLE
shrinkButton() crashes while recording video.

### ISSUE THREAD

**Issue by Adnan1990** [Awalz/SwiftyCam#73]
self.innerCircle is nil and application crashes  in completion 

below is the exact line

self.innerCircle.removeFromSuperview()

**Comment by Awalz** [comment]
I will look into this.

The button included in the SwiftyCam demo project is NOT part of the SwiftyCam framework FYI

**Comment by Minebomber** [comment]
@Awalz can I use the button in my app (at least for testing?)

**Comment by Adnan1990** [comment]
Got it working by updating shrinkButton()

 public func shrinkButton() {
        
```
        if self.innerCircle == nil {
            innerCircle = UIView(frame: CGRect(x: 0, y: 0, width: 1, height: 1))
            innerCircle.center = CGPoint(x: self.bounds.midX, y: self.bounds.midY)
            innerCircle.backgroundColor = UIColor.red
            innerCircle.layer.cornerRadius = innerCircle.frame.size.width / 2
            innerCircle.clipsToBounds = true
            self.addSubview(innerCircle)
            
            self.innerCircle.transform = CGAffineTransform(scaleX: 62.4, y: 62.4)
            self.circleBorder.setAffineTransform(CGAffineTransform(scaleX: 1.352, y: 1.352))
            self.circleBorder.borderWidth = (6 / 1.352)

        }
        UIView.animate(withDuration: 0.3, delay: 0.0, options: .curveEaseOut, animations: {
            self.innerCircle.transform = CGAffineTransform(scaleX: 1.0, y: 1.0)
            self.circleBorder.setAffineTransform(CGAffineTransform(scaleX: 1.0, y: 1.0))
            self.circleBorder.borderWidth = 6.0
        }, completion: { (success) in
            self.innerCircle.removeFromSuperview()
            self.innerCircle.isHidden = true;
        })
    }

```

**Comment by petermarathas** [comment]
@Adnan1990 I ran into the same issue and got it to work by changing this line in SwiftyCamButton.swift:

<code>case .cancelled, .ended, .changed, .failed:</code>

to:

<code>case .cancelled, .ended, .failed:</code>

@Awalz Is the expected functionality to end recording during a changed state? State becomes changed just from a slight movement during long press, and that's how I ran into this issue.

**Comment by Adnan1990** [comment]
Yes i was able to get it working , i just used case .ended and removed others .

**Comment by midgard** [comment]
+1

**Comment by JCsplash** [comment]
+1
