### ISSUE TITLE
Video recoding and crash

### ISSUE THREAD

**Issue by midgard** [Awalz/SwiftyCam#77]
Hi @Awalz,

If i move the my finger on screen while take a video , the application is crashes.

What is your suggestions for this problem solving?

**Comment by mayqiyue** [comment]
+1

**Comment by mayqiyue** [comment]
The log:
Did Begin Recording
Did finish Recording
Did finish Recording
fatal error: unexpectedly found nil while unwrapping an Optional value
2017-07-13 10:32:46.403462+0800 DemoSwiftyCam[2860:903340] fatal error: unexpectedly found nil while unwrapping an Optional value

**Comment by ElliottDiaz** [comment]
I noticed the same thing. Found the location of the bug and if you switch the Long Press method in the swiftycambuttondelegate to this, then it should work, let me know if it does!

@objc fileprivate func LongPress(_ sender:UILongPressGestureRecognizer!)  {
      if (sender.state == UIGestureRecognizerState.ended) {
        invalidateTimer()
        self.delegate?.buttonDidEndLongPress()
      } else if (sender.state == UIGestureRecognizerState.began) {
        self.delegate?.buttonDidBeginLongPress()
        startTimer()
      }

    }

**Comment by Awalz** [comment]
Issue should be fixed in version 2.6.0
