### ISSUE TITLE
Custom buttons in view ignore storyboard layouts

### ISSUE THREAD

**Issue by caesss** [Awalz/SwiftyCam#80]
After I upgraded to 2.4 I ran into an issue with a couple of custom items I was adding to my layout. My outlets were returning nil, so I figured they were not being added to my main vew so I manually added them but in version 2.3 I was able to do this in the storyboard and I was able to assign constraints etc to lay them out. Now I can't. What am I missing? See screenshots attached. 

    override func viewDidLoad() {
        super.viewDidLoad()
       
        cameraDelegate = self
        
        addButtons()
        
        // In version 2.4
        view.addSubview(eventField)
        view.addSubview(eventLabel)
        view.addSubview(backButton)
        view.addSubview(addButton)

        // In version 2.3
//        view.bringSubview(toFront: eventField)
//        view.bringSubview(toFront: eventLabel)
//        view.bringSubview(toFront: backButton)
//        view.bringSubview(toFront: addButton)
    }

![screen shot 2017-06-26 at 9 43 12 pm](https://user-images.githubusercontent.com/1952297/27568877-fa5f3df2-5ab9-11e7-8cc4-cb2663cde014.png)
![simulator screen shot jun 26 2017 9 54 00 pm](https://user-images.githubusercontent.com/1952297/27568879-0125262e-5aba-11e7-93df-47ee83a3e424.png)

**Comment by bui2jp** [comment]
I am facing the same issue and investigating
Is there any update??

**Comment by bui2jp** [comment]
I found one solution. 
We can set NSLayoutConstraint in viewDidLoad(). They works fine.

**Comment by Awalz** [comment]
Issue should be resolved in version 2.6.0

**Comment by derens99** [comment]
Is there another updated solution to this error? I am getting nil when I unwrap my buttons as well. Thanks.
