### ISSUE TITLE
Captured image resolution is limited to 1080x1920

### ISSUE THREAD

**Issue by ShaunakP** [Awalz/SwiftyCam#82]
I am in camera mode and after capturing the image, I see that the image resolution is downscaled to 1080x1920 even though I have 12mp camera. Is there a default setting that we need to override to update the camera capture quality in SwiftyCam?

**Comment by Awalz** [comment]
No, SwiftyCam uses the video feed so both video and images can be captured. The photo that is captured is limited to the resolution of the video feed
