### ISSUE TITLE
SwiftyCamViewControllerDelegate style issue

### ISSUE THREAD

**Issue by markohlebar** [Awalz/SwiftyCam#9]
This is a style issue more than anything... The usual way of writing swift functions is with lower camel case. In the case of `SwiftyCamViewControllerDelegate`, the functions are declared with upper camel case as in:

`func SwiftyCamDidTakePhoto(_ photo:UIImage)`.

My suggestion would be to change the signatures to: 

`func swiftyCam(_ swiftyCam:SwiftyCamViewController, didTake photo:UIImage)`,

or something along those lines to align with Apple's practices for declaring delegate methods.

**Comment by Awalz** [comment]
I appreciate the feedback. I do believe the declarations need work. If I rework them, would you take a look? 

Andrew

**Comment by markohlebar** [comment]
@Awalz checked it now, looks cool! 👍
