### ISSUE TITLE
ContentMode of previewView

### ISSUE THREAD

**Issue by mrfarukturgut** [Awalz/SwiftyCam#90]
Is there any way to set or change the contentMode of cameraView? It is because I am using container view to show camera view not on the whole screen, and if the container view's aspect ratio is not exactly 16:9, then there are some black gaps.

**Comment by MuffinTime** [comment]
You have to add 

videoGravity = .resizeAspectFill;

before line

super.viewDidLoad()

**Comment by mrfarukturgut** [comment]
Thanks!

**Comment by RanaNitishSingh** [comment]
thanks!
