### ISSUE TITLE
Video Crash On Latest CocoaPod Update - UILongPressGestureRecognizer Function - Found Location Of Bug, Please Fix

### ISSUE THREAD

**Issue by ElliottDiaz** [Awalz/SwiftyCam#93]
Just updated the cocoapods and the video would crash as soon as I started recording, definitely scared me. 

I dug into the code and it seems like this is the root of the problem as it works with the prior method. The newer method simply just crashes

***Older Working Method

  /// UILongPressGestureRecognizer Function

    @objc fileprivate func LongPress(_ sender:UILongPressGestureRecognizer!)  {
      if (sender.state == UIGestureRecognizerState.ended) {
        invalidateTimer()
        self.delegate?.buttonDidEndLongPress()
      } else if (sender.state == UIGestureRecognizerState.began) {
        self.delegate?.buttonDidBeginLongPress()
        startTimer()
      }
    }

***Broken New Method - It's a lot cleaner, but I am not sure why its causing the crash.

 /// UILongPressGestureRecognizer Function

    @objc fileprivate func LongPress(_ sender:UILongPressGestureRecognizer!)  {
        switch sender.state {
        case .began:
            delegate?.buttonDidBeginLongPress()
            startTimer()
        case .cancelled, .ended, .changed, .failed:
            invalidateTimer()
            delegate?.buttonDidEndLongPress()
        default:
            break
        }
    }

**Comment by vintagepenguin** [comment]
I tested this & can verify that the fix works. Solid work @ElliottDiaz  💯

**Comment by Awalz** [comment]
Resolved in 2.6.0
